(function(){var _orders=[];var _updated='';var _loaded=false;var _cafeMap='Mosquito Lake';var _tick=null;var CAFE_MAP_KEYS={komarinoe:'Mosquito Lake',losinoe:'Moose Lake',vjunok:'Winding Rivulet',ostrog:'Old Burg Lake',belaya:'Belaya River',kuori:'Kuori Lake',volhov:'Volkhov River',donets:'Seversky Donets',sura:'Sura River',ladoga:'Ladoga Lake',yantarnoe:'Amber Lake',archipelago:'Ladoga archipelago',ahtuba:'Akhtuba River',mednoe:'Cooper Lake',tunguska:'Lower Tunguska River',yama:'Yama River',sea:'Norwegian Sea'};var CAFE_MAP_LABELS={komarinoe:'Komarinoe',losinoe:'Losinoe',vjunok:'Vjunok',ostrog:'Ostrog',belaya:'Belaya',kuori:'Kuori',volhov:'Volkhov',donets:'Donets',sura:'Sura',ladoga:'Ladoga',yantarnoe:'Yantarnoe',archipelago:'Archipiélago',ahtuba:'Akhtuba',mednoe:'Mednoe',tunguska:'Tunguska',yama:'Yama',sea:'Mar Noruega'};function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function secsLeft(expiresAt){var d=expiresAt.endsWith('Z')?new Date(expiresAt):new Date(expiresAt+'Z');return Math.max(0,Math.round((d-Date.now())/1000));}
function totalSecs(expiresAt,addedAt){if(!addedAt)return 30*60;var e=expiresAt.endsWith('Z')?new Date(expiresAt):new Date(expiresAt+'Z');var a=addedAt.endsWith('Z')?new Date(addedAt):new Date(addedAt+'Z');return Math.max(1,Math.round((e-a)/1000));}
function fmtTimeDays(realSecs){var gameSecs=realSecs*24;var gd=Math.floor(gameSecs/86400);var gh=Math.floor((gameSecs%86400)/3600);var gm=Math.floor((gameSecs%3600)/60);var parts=[];if(gd>0)parts.push(gd+' día'+(gd>1?'s':''));if(gh>0)parts.push(gh+' hora'+(gh>1?'s':''));if(gm>0&&gd===0)parts.push(gm+' minuto'+(gm>1?'s':''));return parts.length?parts.join(' '):'menos de 1 minuto';}
function fmtWeight(w){var kg=parseFloat(w)||0;if(kg<1)return Math.round(kg*1000)+' g';return kg.toFixed(3)+' kg';}
function fmtTime(s){s=Math.max(0,Math.round(s));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}
function fmtTimeShort(s){s=Math.max(0,Math.round(s));var h=Math.floor(s/3600);var m=Math.floor((s%3600)/60);var sec=s%60;if(h>0)return h+'h\n'+String(m).padStart(2,'0')+'m';return String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0');}
function fmtTimeLong(s){s=Math.max(0,Math.round(s));var h=Math.floor(s/3600);var m=Math.floor((s%3600)/60);var sec=s%60;if(h>0)return h+' hora'+(h>1?'s':'')+' '+m+' minutos '+sec+' segundos';if(m>0)return m+' minutos '+sec+' segundos';return sec+' segundos';}
function barColor(r){if(r>0.5)return'#3fb950';if(r>0.2)return'#d29922';return'#f85149';}
async function load(){var bust=Math.floor(Date.now()/(60*1000));var urls=['/cafe.json?v='+bust,'https://milatido.github.io/cafe.json?v='+bust];for(var i=0;i<urls.length;i++){try{var res=await fetch(urls[i]);if(!res.ok)continue;var json=await res.json();_orders=json.orders||[];_updated=json.updated||'';_loaded=true;var meta=document.getElementById('cafeMeta');if(meta){meta.textContent='● actualizado '+esc(_updated)+' ('+_orders.length+' pedidos)';meta.style.color='var(--green)';}
return;}catch(e){}}
throw new Error('No se pudo cargar cafe.json');}
function cafeRender(){var now=Date.now();var fromJson=_orders.filter(function(o){return o.map===_cafeMap&&new Date(o.expiresAt.endsWith('Z')?o.expiresAt:o.expiresAt+'Z')>now;});var fromFirestore=_userOrders.filter(function(o){return o.map===_cafeMap&&new Date(o.expiresAt.endsWith('Z')?o.expiresAt:o.expiresAt+'Z')>now;});var active=fromJson.concat(fromFirestore);active.sort(function(a,b){return new Date(a.expiresAt)-new Date(b.expiresAt);});var list=document.getElementById('cafeOrdersList');var cnt=document.getElementById('cafeOrderCount');if(cnt)cnt.textContent=active.length;if(!list)return;if(!active.length){list.innerHTML='<div class="cafe-empty">Sin pedidos activos en este mapa.<br>'
+'<span style="font-size:.74rem;">Se actualizan automáticamente cada 60 segundos.</span></div>';return;}
var CIRC=2*Math.PI*20;list.innerHTML='<div class="cafe-grid">'
+active.map(function(o){var sl=secsLeft(o.expiresAt);var ts=totalSecs(o.expiresAt,o.addedAt)||30*60;var ratio=Math.max(0,Math.min(1,sl/ts));var isUrgent=sl<=5*60;var isWarn=sl<=10*60&&!isUrgent;var cls=isUrgent?' urgent':isWarn?' warning':'';var timerCls=isUrgent?' urgent':isWarn?' warning':'';var gameHoursLeft=(sl*24)/3600;var ghD=Math.floor(gameHoursLeft/24);var ghH=Math.floor(gameHoursLeft%24);var ghM=Math.floor((gameHoursLeft%1)*60);var totalGameH=Math.floor(gameHoursLeft);var totalGameM=Math.floor((gameHoursLeft-totalGameH)*60);var timerDisplay=totalGameH+':'+String(totalGameM).padStart(2,'0');var gameTimeParts=[];if(ghD>0)gameTimeParts.push(ghD+' día'+(ghD>1?'s':''));if(ghH>0)gameTimeParts.push(ghH+' hora'+(ghH>1?'s':''));if(ghM>0&&ghD===0)gameTimeParts.push(ghM+' min');var gameTimeStr=gameTimeParts.join(' ')||'menos de 1 hora';var imgHtml=o.fishImg?'<img src="'+esc(o.fishImg)+'" alt="'+esc(o.fish)+'" onerror="this.parentNode.innerHTML=\'<span class=cafe-no-img>🐟</span>\'">':'<span class="cafe-no-img">🐟</span>';var mapLabel=esc(o.map);return'<div class="cafe-card'+cls+'" style="position:relative;" onmouseenter="this.querySelector(\'.cafe-estado\').style.display=\'flex\'" onmouseleave="this.querySelector(\'.cafe-estado\').style.display=\'none\'">'
+'<div class="cafe-card-img">'
+imgHtml
+'</div>'
+'<div class="cafe-estado" style="display:none;position:absolute;top:60px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,.85);border:1px solid #444;border-radius:6px;padding:8px 12px;z-index:10;min-width:160px;flex-direction:column;gap:2px;pointer-events:none;">'
+'<div style="font-size:.68rem;font-weight:700;color:#aaa;text-transform:uppercase;letter-spacing:.06em;">Estado</div>'
+'<div style="font-size:.82rem;color:#fff;font-weight:600;">El pedido expira en '+gameTimeStr+'</div>'
+'</div>'
+'<div class="cafe-card-body">'
+'<div class="cafe-card-name">'+esc(o.fish)+'</div>'
+'<div class="cafe-card-mapname">'+mapLabel+'</div>'
+'<div class="cafe-card-qty">Cantidad '+esc(o.qty)+' pcs</div>'
+'<div class="cafe-card-weight">Peso a partir de '+fmtWeight(o.weight)+'</div>'
+'</div>'
+'<div class="cafe-card-sep"></div>'
+'<div class="cafe-card-reward">'
+'<span class="cafe-coin-icon">☽</span>'
+esc(o.reward)
+'</div>'+(o._id&&window.CU&&(window.CU.nick===o.reportedBy||window.CU.id===o.reportedBy||window.CU.role==='admin')?'<button onclick="cafeDeleteOrder(\''+o._id+'\',this)" style="width:calc(100% - 28px);display:block;margin:0 14px 10px;padding:5px;border-radius:5px;border:1px solid rgba(248,81,73,.4);background:rgba(248,81,73,.08);color:#f85149;font-family:Exo 2,sans-serif;font-size:.72rem;font-weight:700;cursor:pointer;">🗑 Borrar pedido</button>':'')+'</div>';}).join('')+'</div>';}
var _userOrders=[];var _firestoreUnsub=null;function cafeLoadFirestore(){if(!window.db)return;try{var{collection,query,where,orderBy,onSnapshot}=window._fsImports||{};if(!collection)return;var q=query(collection(window.db,'cafe_pedidos'),where('expiresAt','>',new Date().toISOString()),orderBy('expiresAt','asc'));if(_firestoreUnsub)_firestoreUnsub();_firestoreUnsub=onSnapshot(q,function(snap){_userOrders=snap.docs.map(function(d){return Object.assign({_id:d.id},d.data());});cafeRender();});}catch(e){}}
window.cafeDeleteOrder=async function(docId,btn){if(!window.CU){return;}
if(!confirm('¿Borrar este pedido?'))return;try{btn.disabled=true;btn.textContent='⏳ Borrando...';var{doc,deleteDoc}=window._fsLib||window._fsImports||{};if(!deleteDoc||!doc)throw new Error('Firestore no disponible');await deleteDoc(doc(window.db,'cafe_pedidos',docId));btn.closest('.cafe-card').style.opacity='0.3';setTimeout(function(){btn.closest('.cafe-card').remove();},400);}catch(e){btn.disabled=false;btn.textContent='🗑 Borrar pedido';alert('Error al borrar: '+e.message);}};function cafeCheckLogin(){var btn=document.getElementById('cafeReportBtn');var rightMeta=document.getElementById('cafeMetaRight');if(btn){btn.style.display=window.CU?'block':'none';if(rightMeta)rightMeta.style.marginLeft=window.CU?'8px':'auto';}}
setInterval(cafeCheckLogin,1000);var CAFE_FISH_BY_MAP=null;function getCafeFishForMap(mapFull){var db=window.FISH_DB||[];return db.filter(function(f){return f.maps&&f.maps.some(function(m){return m.n===mapFull;});}).sort(function(a,b){return a.n.localeCompare(b.n);});}
window.cafeOpenReport=function(){var modal=document.getElementById('cafeReportModal');if(!modal)return;window.loadFishDB(function(){var mapLabel=document.getElementById('cafeReportMapLabel');if(mapLabel)mapLabel.textContent=_cafeMap;var sel=document.getElementById('cafeReportFish');if(sel){var fishes=getCafeFishForMap(_cafeMap);sel.innerHTML='<option value="">— Seleccioná el pez —</option>'
+fishes.map(function(f){return'<option value="'+f.n+'" data-trophy="'+f.t+'">'+f.n+' (🏆 '+f.t+')</option>';}).join('');}
modal.style.display='flex';});};window.cafeCloseReport=function(){var modal=document.getElementById('cafeReportModal');if(modal)modal.style.display='none';};window.cafeSubmitReport=async function(){if(!window.CU){return;}
var fish=document.getElementById('cafeReportFish').value;var weightV=parseFloat(document.getElementById('cafeReportWeight').value)||0;var weightU=document.getElementById('cafeReportWeightUnit').value;var weight=weightU==='g'?weightV/1000:weightV;var qty=parseInt(document.getElementById('cafeReportQty').value)||1;var reward=parseFloat(document.getElementById('cafeReportReward').value)||0;var gameH=parseFloat(document.getElementById('cafeReportHours').value)||0;var errEl=document.getElementById('cafeReportErr');var btn=document.getElementById('cafeReportSubmitBtn');if(!fish||!weightV||!gameH){errEl.textContent='Completá todos los campos.';errEl.style.display='block';return;}
errEl.style.display='none';btn.disabled=true;btn.textContent='⏳ Publicando...';var fishData=(window.FISH_DB||[]).find(function(f){return f.n===fish;})||{};var realMs=(gameH/24)*60*60*1000;var now=Date.now();var expiresAt=new Date(now+realMs).toISOString().slice(0,19)+'Z';var addedAt=new Date(now).toISOString().slice(0,19)+'Z';try{var{collection,addDoc}=window._fsImports||{};if(!collection)throw new Error('Firestore no disponible');await addDoc(collection(window.db,'cafe_pedidos'),{map:_cafeMap,fish:fish,fishImg:fishData.img||'',trophyWeight:fishData.t||'',weight:weight,qty:qty,reward:reward,addedAt:addedAt,expiresAt:expiresAt,reportedBy:window.CU.nick||window.CU.id,reportedAt:addedAt});window.cafeCloseReport();['cafeReportFish','cafeReportWeight','cafeReportQty','cafeReportReward','cafeReportHours'].forEach(function(id){var el=document.getElementById(id);if(el){el.value=id==='cafeReportQty'?'1':'';}});}catch(e){errEl.textContent='Error: '+e.message;errEl.style.display='block';}
btn.disabled=false;btn.textContent='Publicar pedido';};document.addEventListener('click',function(e){var modal=document.getElementById('cafeReportModal');if(modal&&e.target===modal)window.cafeCloseReport();});function startTick(){if(_tick)clearInterval(_tick);_tick=setInterval(function(){cafeRender();},1000);}
async function autoReload(){try{await load();cafeRender();}catch(e){}
setTimeout(autoReload,60*1000);}
window.cafeSelectMap=function(btn,mapKey,mapFull){document.querySelectorAll('.cafe-map-btn').forEach(function(b){b.classList.remove('active');});btn.classList.add('active');_cafeMap=mapFull;var lbl=CAFE_MAP_LABELS[mapKey]||mapKey;var e1=document.getElementById('cafeCurrentMapLabel');if(e1)e1.textContent=lbl;cafeRender();};async function init(){var meta=document.getElementById('cafeMeta');if(meta){meta.textContent='● cargando...';meta.style.color='var(--muted)';}
try{await load();}catch(e){if(meta){meta.textContent='● sin datos';meta.style.color='var(--red)';}}
cafeRender();startTick();cafeLoadFirestore();cafeCheckLogin();setTimeout(autoReload,60*1000);}
var _origGpCafe=window.gp;window.gp=function(page){if(typeof _origGpCafe==='function')_origGpCafe(page);if(page==='cafe'){if(!_loaded)init();else cafeRender();}};document.addEventListener('DOMContentLoaded',function(){if(document.getElementById('cafeOrdersList'))init();});})();