(function(){'use strict';let _all=[];let _filtered=[];let _idx=0;let _likes={};let _mode='swipe';let _gFilter='';let _seekFilter='';let _loading=false;let _online=new Set();let _unsubLikes=null;let _unsubMatch=null;let _unsubIncoming=null;let _drag={active:false,startX:0,startY:0,curX:0,curY:0,card:null};window.initMatchPage=function(){if(typeof db==='undefined'||!db){setTimeout(window.initMatchPage,1000);return;}
_loading=false;_idx=0;if(window._sidebarAllOnline){_online=new Set((window._sidebarAllOnline||[]).map(u=>u.id));}
_loadUsers();_subscribeLikes();_subscribeIncomingLikes();};function _loadUsers(){if(_loading)return;if(_all.length>0){_idx=0;_applyMatchFilters();return;}
if(window._matchAllUsers&&window._matchAllUsers.length>0){_all=window._matchAllUsers;_idx=0;_applyMatchFilters();_subscribeRT();return;}
_loading=true;_showSkel();getDocs(collection(db,'users')).then(snap=>{_all=snap.docs.map(d=>({id:d.id,...d.data()})).filter(u=>!u.banned);window._matchAllUsers=_all;_loading=false;_applyMatchFilters();if(typeof window._refreshSidebarMatch==='function')window._refreshSidebarMatch();_subscribeRT();}).catch(err=>{console.warn('match load error:',err);_loading=false;if(window._matchAllUsers&&window._matchAllUsers.length>0){_all=window._matchAllUsers;_applyMatchFilters();}else{_showErr();}});}
function _subscribeRT(){if(_unsubMatch)_unsubMatch();try{_unsubMatch=onSnapshot(collection(db,'users'),snap=>{_all=snap.docs.map(d=>({id:d.id,...d.data()})).filter(u=>!u.banned);window._matchAllUsers=_all;_applyMatchFilters();if(typeof window._refreshSidebarMatch==='function')window._refreshSidebarMatch();},err=>console.warn('match RT err:',err));}catch(e){}}
function _subscribeLikes(){if(!window.CU)return;if(_unsubLikes)_unsubLikes();_unsubLikes=onSnapshot(collection(db,'users',window.CU.id,'matchLikes'),snap=>{_likes={};snap.docs.forEach(d=>{_likes[d.id]=d.data()||true;});_refreshLikeBtn();if(_mode==='grid')_renderGrid();});}
let _knownReceivedLikes=null;function _subscribeIncomingLikes(){if(!window.CU)return;if(_unsubIncoming){_unsubIncoming();_unsubIncoming=null;}
try{_unsubIncoming=onSnapshot(collection(db,'matchIncoming',window.CU.id,'items'),snap=>{if(!snap||snap.empty)return;snap.docChanges().forEach(change=>{if(change.type!=='added')return;const d=change.doc.data();const uid=d.fromUid;if(!uid||uid===window.CU.id)return;if(_knownReceivedLikes===null){if(_knownReceivedLikes===null){_knownReceivedLikes=new Set();snap.docs.forEach(doc=>_knownReceivedLikes.add(doc.id));return;}}
if(_knownReceivedLikes.has(change.doc.id))return;_knownReceivedLikes.add(change.doc.id);const blocked=window.CU?.blocked||[];if(blocked.includes(uid))return;const nick=d.fromNick||'alguien';if(d.superLike){if(typeof showNotifToast==='function')
showNotifToast('⭐ ¡'+nick+' te dio un Super Like! ¡Mirá Match!');if(typeof playNotifSound==='function')playNotifSound();}else{if(typeof showNotifToast==='function')
showNotifToast('💘 ¡A '+nick+' le gustó tu perfil!');if(typeof playNotifSound==='function')playNotifSound();}
_checkMutualMatch(uid);});},err=>console.warn('[matchIncoming] listener err:',err));}catch(e){console.warn('[matchIncoming] setup err:',e);}}
window._resubscribeMatchListeners=function(){_subscribeLikes();_subscribeIncomingLikes();};function _refreshLikeBtn(){const u=_filtered[_idx];if(!u)return;const btn=document.getElementById('mcLikeBtn2');if(!btn)return;const isLiked=!!_likes[u.id];btn.innerHTML=isLiked?'💖':'❤️';if(isLiked)btn.classList.add('liked');else btn.classList.remove('liked');}
window._applyMatchFilters=function(){const ageMin=parseInt(document.getElementById('mfAgeMin2')?.value)||0;const ageMax=parseInt(document.getElementById('mfAgeMax2')?.value)||999;const country=document.getElementById('mfCountry2')?.value||'';const myCountry=(window.CU?.country||'').replace(/^[^\s]+\s/,'').trim().toLowerCase();const blocked=window.CU?.blocked||[];_filtered=_all.filter(u=>{if(u.id===window.CU?.id)return false;if(u.hidden)return false;if(blocked.includes(u.id))return false;if(!u.av||typeof u.av!=='string'||!u.av.startsWith('http'))return false;if(_gFilter){const g=(u.gender||'').toLowerCase();const fL=_gFilter.toLowerCase();if(!g.includes(fL)&&!(fL==='hombre'&&g==='masculino')&&!(fL==='mujer'&&g==='femenino'))return false;}
if(country&&!(u.country||'').includes(country))return false;const age=parseInt(u.age)||0;if(ageMin&&age&&age<ageMin)return false;if(ageMax<999&&age&&age>ageMax)return false;if(_seekFilter){const seeking=u.seeking||[];if(!seeking.includes(_seekFilter))return false;}
return true;});_filtered.sort((a,b)=>{const ac=(a.country||'').replace(/^[^\s]+\s/,'').trim().toLowerCase();const bc=(b.country||'').replace(/^[^\s]+\s/,'').trim().toLowerCase();const aCity=(a.city||a.dept||'').toLowerCase();const bCity=(b.city||b.dept||'').toLowerCase();const myCity=(window.CU?.city||window.CU?.dept||'').toLowerCase();const aCityMatch=myCity&&aCity&&aCity===myCity?3:0;const bCityMatch=myCity&&bCity&&bCity===myCity?3:0;const aCountry=myCountry&&ac===myCountry?2:0;const bCountry=myCountry&&bc===myCountry?2:0;const aOnline=_online.has(a.id)?1:0;const bOnline=_online.has(b.id)?1:0;const aC=_compat(a);const bC=_compat(b);return(bCityMatch+bCountry+bOnline+bC*0.01)-(aCityMatch+aCountry+aOnline+aC*0.01);});if(_idx>=_filtered.length)_idx=0;const pill=document.getElementById('matchCountPill');if(pill)pill.textContent=_filtered.length+' personas';if(_mode==='swipe')_renderSwipeCard(null);else _renderGrid();};window.applyMatchFilters=window._applyMatchFilters;window.resetMatchFilters=_resetMatchFilters;function _resetMatchFilters(){_gFilter='';_seekFilter='';document.querySelectorAll('.mf-pill').forEach(p=>p.classList.remove('on'));const pa=document.getElementById('mfpAll');if(pa)pa.classList.add('on');const ps=document.getElementById('mfpSeekAll');if(ps)ps.classList.add('on');['mfAgeMin2','mfAgeMax2','mfCountry2'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});window._applyMatchFilters();}
function _compat(u){if(!window.CU)return 50;let score=50;const myInterests=(window.CU.interests||[]).map(s=>s.toLowerCase());const theirInterests=(u.interests||[]).map(s=>s.toLowerCase());if(myInterests.length&&theirInterests.length){const common=myInterests.filter(i=>theirInterests.includes(i)).length;score+=Math.min(common*8,30);}
if((window.CU.country||'')===(u.country||'')&&u.country)score+=10;if((window.CU.city||'')===(u.city||u.dept||'')&&(window.CU.city||''))score+=8;if(_online.has(u.id))score+=4;const mySeeking=window.CU.seeking||[];const theirSeek=u.seeking||[];if(mySeeking.length&&theirSeek.length){const common2=mySeeking.filter(s=>theirSeek.includes(s)).length;if(common2>0)score+=6;}
return Math.min(score,99);}
window._setMatchMode=function(mode,btn){_mode=mode;document.querySelectorAll('.match-mode-tab').forEach(t=>t.classList.remove('on'));if(btn)btn.classList.add('on');const sw=document.getElementById('matchSwipeWrap');const gr=document.getElementById('matchGridWrap');if(sw)sw.style.display=mode==='swipe'?'block':'none';if(gr)gr.style.display=mode==='grid'?'block':'none';if(mode==='swipe')_renderSwipeCard(null);else _renderGrid();};function _renderSwipeCard(direction){try{_doRenderSwipe(direction);}
catch(e){console.warn('render swipe err:',e);}}
function _doRenderSwipe(direction){const area=document.getElementById('matchSwipeArea');if(!area)return;_updateNav();if(!_filtered.length){area.innerHTML=`<div class="mc-empty"><div class="mc-empty-icon">🔍</div><div class="mc-empty-title">No se encontraron personas</div><div class="mc-empty-sub">Probá cambiar los filtros o volvé más tarde.</div></div>`;_setActionVis(false);return;}
const u=_filtered[_idx];if(!u){area.innerHTML=`<div class="mc-empty"><div class="mc-empty-icon">🎉</div><div class="mc-empty-title">¡Ya viste todos los perfiles!</div><div class="mc-empty-sub">Volvé más tarde o cambiá los filtros.</div><button onclick="window.initMatchPage()" style="margin-top:16px;padding:10px 24px;background:linear-gradient(135deg,#f33e58,#c4164b);border:none;border-radius:100px;color:#fff;font-weight:800;cursor:pointer;font-size:.85rem;">🔄 Ver de nuevo</button></div>`;_setActionVis(false);return;}
_setActionVis(true);const isOnline=_online.has(u.id);const isLiked=!!_likes[u.id];const compat=_compat(u);const age=u.age?u.age:'';const dept=u.dept||u.city||'';const country=(u.country||'').replace(/^[^\s]+\s/,'').trim();const loc=[dept,country].filter(Boolean).join(', ');const nick=u.nick||u.email?.split('@')[0]||'Usuario';const ini=nick[0].toUpperCase();const quote=u.quote||u.bio||'';const seeking=(u.seeking||[]);const seekLabels={serious:'💑 Algo serio',friend:'🤝 Amigos',casual:'🌊 Casual',chat:'💬 Charlar'};const isVerif=!!(u.av&&u.av.startsWith('http'));const R=18,C=2*Math.PI*R;const fill=C*(1-(compat/100));const compatColor=compat>=75?'#34d399':compat>=50?'#fbbf24':'#f33e58';const photoInner=u.av?`<img class="mc-img" src="${_esc(u.av)}" loading="lazy" onerror="this.style.display='none';this.nextSibling.style.display='flex';">
       <div class="mc-photo-initials" style="display:none;width:100%;height:100%;background:linear-gradient(135deg,#2a1f3d,#1a0a2e);display:none;align-items:center;justify-content:center;font-size:6rem;font-weight:900;color:#f33e58;">${ini}</div>`:`<div style="width:100%;height:100%;background:linear-gradient(135deg,#2a1f3d,#1a0a2e);display:flex;align-items:center;justify-content:center;font-size:6rem;font-weight:900;color:#f33e58;">${ini}</div>`;const seekChips=seeking.slice(0,2).map(s=>seekLabels[s]?`<span class="mc-chip seek">${_esc(seekLabels[s])}</span>`:'').join('');const extraChips=[];if(isOnline)extraChips.push('<span class="mc-chip online">🟢 Online</span>');if(isVerif)extraChips.push('<span class="mc-chip verif">✓ Verificado</span>');if(u.role==='premium'||u.role==='admin')extraChips.push('<span class="mc-chip" style="background:rgba(251,191,36,.2);border-color:rgba(251,191,36,.4);color:#fbbf24;">⭐ Premium</span>');const oldCard=area.querySelector('.mc-card');if(oldCard&&direction){const anim=direction==='next'?'swipeLeft':'swipeRight';oldCard.style.animation=`${anim} .3s ease forwards`;setTimeout(()=>oldCard.remove(),280);}else if(oldCard){oldCard.remove();}
const skel=area.querySelector('.mc-skel-card');if(skel)skel.remove();const card=document.createElement('div');card.className='mc-card';if(direction)card.style.animation='cardIn .35s cubic-bezier(.34,1.56,.64,1) both';card.dataset.uid=u.id;card.dataset.nick=nick;card.innerHTML=`
    ${photoInner}
    <div class="mc-grad"></div>
    ${isOnline?'<div class="mc-online-badge"><div class="mc-online-dot"></div>En línea</div>':''}
    ${isVerif?'<div class="mc-verif-badge">✓</div>':''}
    <!-- Compat ring (solo si verif no está en misma posición) -->
    ${!isVerif?`<div class="mc-compat-ring"style="position:absolute;top:14px;right:14px;z-index:5;"><svg viewBox="0 0 44 44"><circle class="cr-bg"cx="22"cy="22"r="${R}"/><circle class="cr-fill"cx="22"cy="22"r="${R}"stroke="${compatColor}"stroke-dasharray="${C}"stroke-dashoffset="${fill}"/></svg><div class="mc-compat-pct"style="color:${compatColor};">${compat}%</div></div>`:
    `<div style="position:absolute;top:48px;right:14px;z-index:5;display:flex;align-items:center;gap:4px;background:rgba(0,0,0,.55);backdrop-filter:blur(6px);border:1px solid rgba(255,255,255,.12);border-radius:100px;padding:3px 8px;"><span style="font-size:.6rem;font-weight:800;color:${compatColor};">${compat}%</span><span style="font-size:.55rem;color:rgba(255,255,255,.5);">compat.</span></div>`}
    <!-- Indicadores swipe -->
    <div class="mc-swipe-indicator nope" id="mcIndNope">✕ NOPE</div>
    <div class="mc-swipe-indicator like" id="mcIndLike">LIKE ♥</div>
    <div class="mc-swipe-indicator super" id="mcIndSuper">⭐ SUPER</div>
    <!-- Info -->
    <div class="mc-info">
      <div class="mc-name-row">
        <span class="mc-name">${_esc(nick)}</span>
        ${age?`<span class="mc-age">${_esc(age)}</span>`:''}
      </div>
      ${loc?`<div class="mc-loc">📍 ${_esc(loc)}</div>`:''}
      ${quote?`<div class="mc-quote">"${_esc(quote)}"</div>`:''}
      <div class="mc-chips">
        ${seekChips}
        ${extraChips.join('')}
      </div>
    </div>`;area.appendChild(card);_refreshLikeBtn();_attachSwipeGestures(card,u.id,nick);}
function _attachSwipeGestures(card,uid,nick){const THRESHOLD_X=90;const THRESHOLD_Y=-110;function onStart(x,y){_drag.active=true;_drag.startX=x;_drag.startY=y;_drag.curX=x;_drag.curY=y;_drag.card=card;card.style.transition='none';}
function onMove(x,y){if(!_drag.active)return;_drag.curX=x;_drag.curY=y;const dx=x-_drag.startX,dy=y-_drag.startY;const rot=dx*0.07;card.style.transform=`translate(${dx}px,${dy}px) rotate(${rot}deg)`;const nope=card.querySelector('#mcIndNope');const like=card.querySelector('#mcIndLike');const sup=card.querySelector('#mcIndSuper');const absDx=Math.abs(dx),absDy=Math.abs(dy);if(dy<-60&&absDy>absDx){if(nope)nope.style.opacity='0';if(like)like.style.opacity='0';if(sup)sup.style.opacity=Math.min(Math.abs(dy)/THRESHOLD_Y*-1,1)+'';}else if(dx>30){if(nope)nope.style.opacity='0';if(sup)sup.style.opacity='0';if(like)like.style.opacity=Math.min(dx/THRESHOLD_X,1)+'';}else if(dx<-30){if(like)like.style.opacity='0';if(sup)sup.style.opacity='0';if(nope)nope.style.opacity=Math.min(Math.abs(dx)/THRESHOLD_X,1)+'';}else{if(nope)nope.style.opacity='0';if(like)like.style.opacity='0';if(sup)sup.style.opacity='0';}}
function onEnd(){if(!_drag.active)return;_drag.active=false;const dx=_drag.curX-_drag.startX,dy=_drag.curY-_drag.startY;card.style.transition='transform .3s ease, opacity .3s ease';const nope=card.querySelector('#mcIndNope');const like=card.querySelector('#mcIndLike');const sup=card.querySelector('#mcIndSuper');if(nope)nope.style.opacity='0';if(like)like.style.opacity='0';if(sup)sup.style.opacity='0';if(dy<THRESHOLD_Y&&Math.abs(dy)>Math.abs(dx)){card.style.animation='swipeUp .4s ease forwards';setTimeout(()=>{_doSuperLike(uid,nick);},350);}else if(dx>THRESHOLD_X){card.style.animation='swipeRight .35s ease forwards';setTimeout(()=>{_doLike(uid);},300);}else if(dx<-THRESHOLD_X){card.style.animation='swipeLeft .35s ease forwards';setTimeout(()=>{_advance();},280);}else{card.style.transform='';}}
card.addEventListener('touchstart',e=>{const t=e.touches[0];onStart(t.clientX,t.clientY);},{passive:true});card.addEventListener('touchmove',e=>{const t=e.touches[0];onMove(t.clientX,t.clientY);e.preventDefault();},{passive:false});card.addEventListener('touchend',()=>onEnd());card.addEventListener('mousedown',e=>{onStart(e.clientX,e.clientY);e.preventDefault();});document.addEventListener('mousemove',e=>{if(_drag.active)onMove(e.clientX,e.clientY);});document.addEventListener('mouseup',()=>{if(_drag.active)onEnd();});}
window._matchNope=function(){const card=document.querySelector('.mc-card');if(card){card.style.animation='swipeLeft .35s ease forwards';}
setTimeout(_advance,300);};window._matchLike=async function(){const u=_filtered[_idx];if(!u)return;const card=document.querySelector('.mc-card');if(card){card.style.animation='swipeRight .35s ease forwards';}
setTimeout(()=>_doLike(u.id),300);};window._matchSuperLike=async function(){const u=_filtered[_idx];if(!u)return;const card=document.querySelector('.mc-card');if(card){card.style.animation='swipeUp .4s ease forwards';}
setTimeout(()=>_doSuperLike(u.id,u.nick||''),350);};window._matchViewProfile=function(){const u=_filtered[_idx];if(!u)return;if(typeof openUserProfile==='function')openUserProfile(u.id,u.nick||'');};window._matchShowInfo=function(){const u=_filtered[_idx];if(!u)return;const compat=_compat(u);const compatColor=compat>=75?'#34d399':compat>=50?'#fbbf24':'#f33e58';const seekLabels={serious:'💑 Algo serio',friend:'🤝 Amigos',casual:'🌊 Casual',chat:'💬 Charlar'};const seekChips=(u.seeking||[]).map(s=>seekLabels[s]||s).filter(Boolean).join(' · ');const loc=[u.city||u.dept||'',(u.country||'').replace(/^[^\s]+\s/,'').trim()].filter(Boolean).join(', ');const existing=document.getElementById('_matchInfoModal');if(existing)existing.remove();const overlay=document.createElement('div');overlay.id='_matchInfoModal';overlay.style.cssText='position:fixed;inset:0;z-index:99999;display:flex;align-items:flex-end;justify-content:center;background:rgba(0,0,0,.6);backdrop-filter:blur(4px);';overlay.innerHTML=`
    <div style="background:#1a1025;border:1px solid rgba(255,255,255,.12);border-radius:20px 20px 0 0;padding:24px 20px 36px;width:100%;max-width:520px;animation:cardIn .3s cubic-bezier(.34,1.56,.64,1) both;">
      <div style="width:40px;height:4px;background:rgba(255,255,255,.2);border-radius:2px;margin:0 auto 20px;"></div>
      <!-- Avatar + nombre -->
      <div style="display:flex;align-items:center;gap:14px;margin-bottom:18px;">
        <div style="width:64px;height:64px;border-radius:50%;overflow:hidden;border:2px solid rgba(255,255,255,.15);flex-shrink:0;background:#2a1f3d;">
          ${u.av ? `<img src="${_esc(u.av)}"style="width:100%;height:100%;object-fit:cover;">` : `<div style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;font-size:1.8rem;font-weight:900;color:#f33e58;">${(u.nick||'?')[0].toUpperCase()}</div>`}
        </div>
        <div style="flex:1;min-width:0;">
          <div style="font-size:1.1rem;font-weight:800;color:#fff;">${_esc(u.nick||'Usuario')}${u.age?`<span style="font-size:.85rem;color:rgba(255,255,255,.5);font-weight:400;">${_esc(u.age)}</span>`:''}</div>
          ${loc ? `<div style="font-size:.78rem;color:rgba(255,255,255,.5);margin-top:2px;">📍 ${_esc(loc)}</div>` : ''}
          <div style="margin-top:6px;display:inline-flex;align-items:center;gap:5px;background:rgba(${compat>=75?'52,211,153':compat>=50?'251,191,36':'243,62,88'},.15);border:1px solid rgba(${compat>=75?'52,211,153':compat>=50?'251,191,36':'243,62,88'},.4);border-radius:100px;padding:3px 10px;">
            <span style="font-size:.7rem;font-weight:800;color:${compatColor};">${compat}% compatibilidad</span>
          </div>
        </div>
      </div>
      <!-- Bio -->
      ${(u.bio||u.quote) ? `<div style="background:rgba(255,255,255,.04);border-radius:12px;padding:12px 14px;margin-bottom:14px;font-size:.85rem;color:rgba(255,255,255,.7);line-height:1.6;">"${_esc(u.bio||u.quote)}"</div>` : ''}
      <!-- Detalles -->
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:18px;">
        ${u.favFish?`<div style="background:rgba(255,255,255,.04);border-radius:10px;padding:10px 12px;font-size:.78rem;color:rgba(255,255,255,.6);">🎣<strong style="color:#fff;">${_esc(u.favFish)}</strong></div>`:''}
        ${u.favMap?`<div style="background:rgba(255,255,255,.04);border-radius:10px;padding:10px 12px;font-size:.78rem;color:rgba(255,255,255,.6);">🗺️<strong style="color:#fff;">${_esc(u.favMap)}</strong></div>`:''}
        ${seekChips?`<div style="background:rgba(243,62,88,.08);border:1px solid rgba(243,62,88,.2);border-radius:10px;padding:10px 12px;font-size:.78rem;color:rgba(255,255,255,.7);grid-column:1/-1;">💘 Busca:<strong style="color:#f33e58;">${_esc(seekChips)}</strong></div>`:''}
      </div>
      <!-- Botones -->
      <div style="display:flex;gap:10px;">
        <button onclick="document.getElementById('_matchInfoModal').remove();openUserProfile('${_esc(u.id)}','${_esc(u.nick||'')}');"
          style="flex:1;padding:13px;background:rgba(46,196,182,.15);border:1px solid rgba(46,196,182,.3);border-radius:12px;color:#2ec4b6;font-size:.85rem;font-weight:700;cursor:pointer;font-family:'Exo 2',sans-serif;">
          👤 Ver perfil completo
        </button>
        <button onclick="document.getElementById('_matchInfoModal').remove();"
          style="flex:1;padding:13px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);border-radius:12px;color:rgba(255,255,255,.7);font-size:.85rem;font-weight:700;cursor:pointer;">
          Cerrar
        </button>
      </div>
    </div>`;overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove();});document.body.appendChild(overlay);};async function _doLike(uid){if(!window.CU){toast('Iniciá sesión para dar likes','err');return;}
const likeRef=doc(db,'users',window.CU.id,'matchLikes',uid);if(_likes[uid]){try{delete _likes[uid];await deleteDoc(likeRef);_refreshLikeBtn();if(_mode==='grid')_renderGrid();}catch(e){console.warn('unlike err:',e);}
_advance();return;}
try{const existing=await getDoc(likeRef);if(existing.exists()){_likes[uid]=existing.data()||true;_advance();return;}}catch(e){console.warn('like dup check err:',e);}
_likes[uid]=true;_refreshLikeBtn();if(_mode==='grid')_renderGrid();_advance();try{await setDoc(likeRef,{ts:Date.now(),nick:window.CU.nick||'',av:window.CU.av||'',superLike:false,fromUid:window.CU.id||''});}catch(e){console.warn('like err:',e);toast('No se pudo guardar el like','err');delete _likes[uid];return;}
if(typeof sendNotifToUser==='function'){try{const blocked=window.CU?.blocked||[];if(!blocked.includes(uid)){const notif={text:'💘 ¡A '+(window.CU.nick||'alguien')+' le gustó tu perfil! Entrá a Match.',time:Date.now(),read:false,type:'match_like',fromUid:window.CU.id||'',fromAv:window.CU.av||'',fromNick:window.CU.nick||''};await updateDoc(doc(db,'users',uid),{notifs:arrayUnion(notif)});try{await setDoc(doc(db,'matchIncoming',uid,'items',window.CU.id),{fromUid:window.CU.id||'',fromNick:window.CU.nick||'',fromAv:window.CU.av||'',superLike:false,ts:Date.now()});}catch(me){console.warn('matchIncoming write err:',me);}}}catch(ne){console.warn('like notif err:',ne);}}
_checkMutualMatch(uid);}
async function _doSuperLike(uid,nick){if(!window.CU){toast('Iniciá sesión para dar Super Like','err');return;}
const likeRef=doc(db,'users',window.CU.id,'matchLikes',uid);if(_likes[uid]){_advance();return;}
try{const existing=await getDoc(likeRef);if(existing.exists()){_likes[uid]=existing.data()||true;_advance();return;}}catch(e){console.warn('superlike dup check err:',e);}
_likes[uid]=true;_refreshLikeBtn();if(_mode==='grid')_renderGrid();_advance();_spawnStars();toast('⭐ ¡Super Like enviado a '+_esc(nick||'')+'!','ok');try{await setDoc(likeRef,{ts:Date.now(),nick:window.CU.nick||'',av:window.CU.av||'',superLike:true,fromUid:window.CU.id||''});}catch(e){console.warn('superlike err:',e);delete _likes[uid];return;}
try{const blocked=window.CU?.blocked||[];if(!blocked.includes(uid)){const notif={text:'⭐ ¡'+(window.CU.nick||'alguien')+' te dio un Super Like! ¡Revisá Match!',time:Date.now(),read:false,type:'match_superlike',fromUid:window.CU.id||'',fromAv:window.CU.av||'',fromNick:window.CU.nick||''};await updateDoc(doc(db,'users',uid),{notifs:arrayUnion(notif)});try{await setDoc(doc(db,'matchIncoming',uid,'items',window.CU.id),{fromUid:window.CU.id||'',fromNick:window.CU.nick||'',fromAv:window.CU.av||'',superLike:true,ts:Date.now()});}catch(me){console.warn('matchIncoming superlike write err:',me);}}}catch(ne){console.warn('superlike notif err:',ne);}
_checkMutualMatch(uid);}
async function _checkMutualMatch(uid){try{const theirLike=await getDoc(doc(db,'users',uid,'matchLikes',window.CU.id));if(!theirLike.exists())return;const matchedUser=_all.find(x=>x.id===uid);const matchedNick=matchedUser?.nick||'alguien';const matchedAv=matchedUser?.av||'';const nowTs=Date.now();const ids=[window.CU.id,uid].sort();const matchId=ids[0]+'_'+ids[1];let alreadyMatched=false;try{const existingMatch=await getDoc(doc(db,'matches',matchId));alreadyMatched=existingMatch.exists();}catch(e){console.warn('match check err:',e);}
if(alreadyMatched)return;try{await setDoc(doc(db,'matches',matchId),{users:ids,user1:ids[0],user2:ids[1],user1Nick:ids[0]===window.CU.id?(window.CU.nick||''):matchedNick,user2Nick:ids[1]===window.CU.id?(window.CU.nick||''):matchedNick,user1Av:ids[0]===window.CU.id?(window.CU.av||''):matchedAv,user2Av:ids[1]===window.CU.id?(window.CU.av||''):matchedAv,createdAt:nowTs,chatEnabled:true});}catch(e){console.warn('match save err:',e);}
_showMutualMatch(uid,matchedNick,matchedAv);try{await updateDoc(doc(db,'users',window.CU.id),{notifs:arrayUnion({text:'🎉 ¡Match con '+matchedNick+'! Los dos se dieron like 💖',time:nowTs+1,read:false,type:'match_mutual',matchUid:uid,fromUid:uid,fromAv:matchedAv,fromNick:matchedNick})});}catch(e){console.warn('match self notif err:',e);}
if(uid!==window.CU.id){try{await updateDoc(doc(db,'users',uid),{notifs:arrayUnion({text:'🎉 ¡Es un match con '+(window.CU.nick||'alguien')+'! Los dos se dieron like 💖',time:nowTs,read:false,type:'match_mutual',matchUid:window.CU.id,fromUid:window.CU.id||'',fromAv:window.CU.av||'',fromNick:window.CU.nick||''})});}catch(e){console.warn('match mutual notif err:',e);}}}catch(e){console.warn('mutual match check err:',e);}}
function _advance(){if(_idx<_filtered.length-1){_idx++;_renderSwipeCard('next');}
else{_renderSwipeCard(null);}
_updateNav();}
window._matchPrev=function(){if(_idx<=0)return;_idx--;_renderSwipeCard('prev');_updateNav();};window._matchNext=function(){if(_idx>=_filtered.length-1)return;_idx++;_renderSwipeCard('next');_updateNav();};function _updateNav(){const prev=document.getElementById('mcPrevBtn2');const next=document.getElementById('mcNextBtn2');const cnt=document.getElementById('mcCounter2');if(prev)prev.disabled=(_idx<=0);if(next)next.disabled=(_idx>=_filtered.length-1);if(cnt)cnt.textContent=_filtered.length?`${_idx+1} / ${_filtered.length}`:'';}
function _setActionVis(vis){const row=document.getElementById('mcActionRow');if(row)row.style.visibility=vis?'visible':'hidden';}
function _renderGrid(){const area=document.getElementById('matchGridArea');if(!area)return;if(!_filtered.length){area.innerHTML=`<div class="mc-empty" style="grid-column:1/-1;"><div class="mc-empty-icon">🔍</div><div class="mc-empty-title">Sin resultados</div><div class="mc-empty-sub">Cambiá los filtros.</div></div>`;return;}
area.innerHTML=_filtered.slice(0,40).map((u,i)=>{const nick=u.nick||u.email?.split('@')[0]||'Usuario';const ini=nick[0].toUpperCase();const isOnline=_online.has(u.id);const isLiked=!!_likes[u.id];const compat=_compat(u);const age=u.age||'';const dept=u.dept||u.city||'';const compatColor=compat>=75?'#34d399':compat>=50?'#fbbf24':'#f33e58';const photo=u.av?`<img class="mc-grid-img" src="${_esc(u.av)}" loading="lazy" onerror="this.src='';this.style.display='none'">`:`<div style="width:100%;height:100%;background:linear-gradient(135deg,#2a1f3d,#1a0a2e);display:flex;align-items:center;justify-content:center;font-size:3.5rem;font-weight:900;color:#f33e58;">${ini}</div>`;return`
      <div class="mc-grid-card" onclick="_gridCardClick(${i})">
        ${photo}
        <div class="mc-grid-grad"></div>
        ${isOnline?'<div class="mc-grid-online"></div>':''}
        <div class="mc-grid-compat" style="color:${compatColor};">${compat}%</div>
        ${isLiked?'<div class="mc-grid-liked">💖</div>':''}
        <div class="mc-grid-info">
          <div class="mc-grid-name">${_esc(nick)}${age?`<span style="font-weight:400;opacity:.75;">,${_esc(age)}</span>`:''}
          </div>
          <div class="mc-grid-sub">${dept?'📍 '+_esc(dept):''}</div>
        </div>
      </div>`;}).join('');}
window._gridCardClick=function(i){_idx=i;_setMatchMode('swipe',document.getElementById('mTabSwipe'));};window._setGender=function(val,btn){_gFilter=val;document.querySelectorAll('.mf-pill[id^="mfp"]').forEach(p=>{if(['mfpAll','mfpM','mfpF'].includes(p.id))p.classList.remove('on');});if(btn)btn.classList.add('on');window._applyMatchFilters();};window.setGenderFilter=function(val,btn){window._setGender(val,btn);};window._setSeek=function(val,btn){_seekFilter=val;document.querySelectorAll('.mf-pill[id^="mfpSeek"]').forEach(p=>p.classList.remove('on'));if(btn)btn.classList.add('on');window._applyMatchFilters();};window._toggleMatchFilters=function(){const panel=document.getElementById('mfPanel');const btn=document.getElementById('mhFilterBtn');if(!panel)return;panel.classList.toggle('open');if(btn)btn.classList.toggle('active',panel.classList.contains('open'));};window._matchBoost=function(){toast('⚡ Boost activado por 30 minutos — más personas verán tu perfil','ok');};function _spawnStars(){for(let i=0;i<12;i++){setTimeout(()=>{const s=document.createElement('div');s.style.cssText=`position:fixed;pointer-events:none;z-index:9999;font-size:${1+Math.random()*1.4}rem;
        left:${10+Math.random()*80}%;bottom:${10+Math.random()*30}%;
        animation:_mfxFloat ${1.8+Math.random()*2}s linear forwards;`;s.textContent=['⭐','✨','💫','🌟'][Math.floor(Math.random()*4)];document.body.appendChild(s);setTimeout(()=>s.remove(),4000);},i*80);}}
function _showMutualMatch(uid,name,av){if(!document.getElementById('_matchFxStyles')){const s=document.createElement('style');s.id='_matchFxStyles';s.textContent=`
      @keyframes _mfxHeartPop{0%{transform:scale(0) rotate(-20deg);opacity:0}60%{transform:scale(1.4) rotate(8deg);opacity:1}80%{transform:scale(.9) rotate(-4deg)}100%{transform:scale(1) rotate(0)}}
      @keyframes _mfxSlideUp{from{transform:translateY(60px) scale(.92);opacity:0}to{transform:translateY(0) scale(1);opacity:1}}
      @keyframes _mfxPulseGlow{0%,100%{box-shadow:0 0 30px rgba(224,64,251,.5),0 0 80px rgba(224,64,251,.15)}50%{box-shadow:0 0 60px rgba(224,64,251,.85),0 0 120px rgba(224,64,251,.35)}}
      @keyframes _mfxFloat{0%{transform:translateY(0) rotate(0) scale(1);opacity:1}100%{transform:translateY(-110vh) rotate(720deg) scale(.3);opacity:0}}
      @keyframes _mfxConfetti{0%{transform:translateY(-20px) rotate(0);opacity:1}100%{transform:translateY(110vh) rotate(600deg);opacity:0}}
      @keyframes _mfxShimmer{0%{background-position:-200% center}100%{background-position:200% center}}
      ._mfx-heart-emoji{position:fixed;pointer-events:none;z-index:99998;animation:_mfxFloat linear forwards;}
      ._mfx-confetti{position:fixed;pointer-events:none;z-index:99998;width:10px;height:10px;border-radius:2px;animation:_mfxConfetti linear forwards;}
      ._mfx-avatar-ring{animation:_mfxPulseGlow 1.5s ease-in-out infinite;border-radius:50%;border:3px solid #e040fb;width:80px;height:80px;object-fit:cover;}
      ._mfx-title-shimmer{background:linear-gradient(90deg,#e040fb,#f48fb1,#fff,#e040fb);background-size:200% auto;-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;animation:_mfxShimmer 2s linear infinite;}`;document.head.appendChild(s);}
const hearts=['❤️','💖','💗','💕','💞','💓'];for(let i=0;i<18;i++){setTimeout(()=>{const h=document.createElement('div');h.className='_mfx-heart-emoji';h.textContent=hearts[Math.floor(Math.random()*hearts.length)];h.style.left=Math.random()*100+'vw';h.style.bottom='-60px';h.style.fontSize=(1.2+Math.random()*2.2)+'rem';const dur=2.2+Math.random()*3;h.style.animationDuration=dur+'s';document.body.appendChild(h);setTimeout(()=>h.remove(),dur*1000+100);},i*120);}
const cc=['#e040fb','#f48fb1','#2ec4b6','#ffd700','#ff6b6b','#a78bfa','#34d399'];for(let i=0;i<40;i++){setTimeout(()=>{const c=document.createElement('div');c.className='_mfx-confetti';c.style.left=Math.random()*100+'vw';c.style.top='-20px';c.style.background=cc[Math.floor(Math.random()*cc.length)];c.style.width=(6+Math.random()*10)+'px';c.style.height=c.style.width;c.style.borderRadius=Math.random()>.5?'50%':'2px';const dur=2.5+Math.random()*2.5;c.style.animationDuration=dur+'s';c.style.animationDelay=Math.random()*1.2+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),(dur+1.5)*1000);},i*60);}
try{const ctx=new(window.AudioContext||window.webkitAudioContext)();[[523.25,0],[659.25,.12],[783.99,.24],[1046.5,.38],[1318.5,.54]].forEach(([f,d])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(0,ctx.currentTime+d);g.gain.linearRampToValueAtTime(.32,ctx.currentTime+d+.06);g.gain.linearRampToValueAtTime(0,ctx.currentTime+d+.45);o.start(ctx.currentTime+d);o.stop(ctx.currentTime+d+.5);});}catch(e){}
if(typeof Notification!=='undefined'&&Notification.permission==='granted'){try{new Notification('💘 ¡Match en MiLatido!',{body:'Vos y '+name+' se dieron like. ¡Escribile!',icon:'/icon-192.png'});}catch(e){}}
const existing=document.getElementById('_matchMutualOverlay');if(existing)existing.remove();const overlay=document.createElement('div');overlay.id='_matchMutualOverlay';overlay.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;z-index:99999;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.82);backdrop-filter:blur(10px);';const avHtml=av?`<img src="${_esc(av)}" class="_mfx-avatar-ring" onerror="this.style.display='none'">`:`<div style="width:80px;height:80px;border-radius:50%;background:linear-gradient(135deg,#e040fb,#9c27b0);display:flex;align-items:center;justify-content:center;font-size:2.2rem;">💜</div>`;const myAvHtml=window.CU?.av?`<img src="${_esc(window.CU.av)}" class="_mfx-avatar-ring" onerror="this.style.display='none'">`:`<div style="width:80px;height:80px;border-radius:50%;background:linear-gradient(135deg,#2ec4b6,#0d9488);display:flex;align-items:center;justify-content:center;font-size:2.2rem;">💚</div>`;overlay.innerHTML=`
    <div style="background:linear-gradient(160deg,#1a0a1e 0%,#0d1117 60%,#0a1628 100%);border:1.5px solid rgba(224,64,251,.5);border-radius:28px;padding:40px 32px 32px;max-width:340px;width:92%;text-align:center;animation:_mfxSlideUp .45s cubic-bezier(.34,1.56,.64,1) both;position:relative;overflow:hidden;">
      <div style="position:absolute;top:-60px;left:50%;transform:translateX(-50%);width:220px;height:220px;background:radial-gradient(circle,rgba(224,64,251,.18) 0%,transparent 70%);pointer-events:none;"></div>
      <div style="font-size:4.5rem;line-height:1;margin-bottom:12px;animation:_mfxHeartPop .6s cubic-bezier(.34,1.56,.64,1) both;">💖</div>
      <div class="_mfx-title-shimmer" style="font-family:Orbitron,monospace;font-size:1.6rem;font-weight:900;letter-spacing:2px;margin-bottom:4px;">¡ES UN MATCH!</div>
      <div style="font-size:.88rem;color:#c9a0dc;margin-bottom:24px;letter-spacing:.5px;">Se gustaron mutuamente 💕</div>
      <div style="display:flex;align-items:center;justify-content:center;gap:16px;margin-bottom:22px;">
        ${myAvHtml}
        <div style="display:flex;flex-direction:column;align-items:center;gap:4px;">
          <div style="font-size:1.6rem;">💞</div>
          <div style="width:2px;height:20px;background:linear-gradient(to bottom,#e040fb,transparent);border-radius:2px;"></div>
        </div>
        ${avHtml}
      </div>
      <div style="font-size:.92rem;color:#050505;margin-bottom:26px;line-height:1.6;">
        <strong style="color:#f9a8d4;">${_esc(window.CU?.nick||'Vos')}</strong>
        <span style="color:#65676b;"> y </span>
        <strong style="color:#f48fb1;">${_esc(name)}</strong>
        <br><span style="color:#65676b;font-size:.82rem;">se dieron like ✨</span>
      </div>
      <div style="display:flex;gap:10px;justify-content:center;">
        <button onclick="(function(el){typeof openChatWith==='function'&&openChatWith('${_esc(uid)}','${_esc(name)}');el.closest('#_matchMutualOverlay').remove();})(this)"
          style="background:linear-gradient(135deg,#e040fb,#9c27b0);color:#fff;border:none;border-radius:100px;padding:13px 24px;font-size:.88rem;font-weight:800;cursor:pointer;font-family:'Exo 2',sans-serif;box-shadow:0 4px 20px rgba(224,64,251,.4);transition:transform .15s,box-shadow .15s;"
          onmouseover="this.style.transform='scale(1.05)'" onmouseout="this.style.transform=''">
          💬 Enviar mensaje
        </button>
        <button onclick="document.getElementById('_matchMutualOverlay').remove();"
          style="background:rgba(255,255,255,.07);color:#050505;border:1px solid rgba(255,255,255,.15);border-radius:100px;padding:13px 18px;font-size:.86rem;font-weight:700;cursor:pointer;">
          Ahora no
        </button>
      </div>
    </div>`;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove();});setTimeout(()=>{if(overlay.parentNode){overlay.style.opacity='0';overlay.style.transition='opacity .5s';setTimeout(()=>overlay.remove(),500);}},11000);}
function _showSkel(){const area=document.getElementById('matchSwipeArea');if(!area)return;area.innerHTML='<div class="mc-skel-card"></div>';}
function _showErr(){const area=document.getElementById('matchSwipeArea');if(!area)return;area.innerHTML=`<div class="mc-empty"><div class="mc-empty-icon">⚠️</div><div class="mc-empty-title">Error al cargar</div><div class="mc-empty-sub"><button onclick="window.initMatchPage()" style="margin-top:12px;padding:9px 22px;background:var(--accent);border:none;border-radius:100px;color:#000;font-weight:800;cursor:pointer;">🔄 Reintentar</button></div></div>`;}
function _esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}})();