(function(){'use strict';const SALAS_DATA=[{id:'general',nombre:'General',emoji:'🌐',adultos:false,salas:[{id:'bienvenida',nombre:'Bienvenida',emoji:'👋',desc:'Presentate a la comunidad'},{id:'general',nombre:'General',emoji:'💬',desc:'Conversación libre'},{id:'uruguay',nombre:'Uruguay 🇺🇾',emoji:'🌿',desc:'Todo sobre Uruguay'},{id:'argentina',nombre:'Argentina 🇦🇷',emoji:'🧉',desc:'Todo sobre Argentina'},{id:'humor',nombre:'Humor & Memes',emoji:'😂',desc:'Para reírse un rato'},]},{id:'citas',nombre:'Citas & Amor',emoji:'💕',adultos:false,salas:[{id:'flirteo',nombre:'Flirteo',emoji:'😏',desc:'Para los piropos'},{id:'consejos-amor',nombre:'Consejos de Amor',emoji:'💌',desc:'Pedí o dá consejos'},{id:'solter@s',nombre:'Solter@s',emoji:'💔',desc:'Para los que están solteros'},{id:'relaciones',nombre:'Relaciones',emoji:'💑',desc:'En pareja y queriendo más'},]},{id:'hobbies',nombre:'Hobbies',emoji:'🎨',adultos:false,salas:[{id:'musica',nombre:'Música',emoji:'🎵',desc:'Compartí lo que escuchás'},{id:'series-pelis',nombre:'Series & Pelis',emoji:'🎬',desc:'Recomendaciones y debates'},{id:'deportes',nombre:'Deportes',emoji:'⚽',desc:'Fútbol, básquet y más'},{id:'gaming',nombre:'Gaming',emoji:'🎮',desc:'Videojuegos y torneos'},{id:'cocina',nombre:'Cocina & Comida',emoji:'🍕',desc:'Recetas y antojos'},]},{id:'adultos',nombre:'Adultos',emoji:'🔞',adultos:true,salas:[{id:'adultos-general',nombre:'General +18',emoji:'🔥',desc:'Conversación sin filtros'},{id:'adultos-flirteo',nombre:'Flirteo Caliente',emoji:'💋',desc:'Solo para mayores'},{id:'adultos-picante',nombre:'Zona Picante',emoji:'🌶️',desc:'Contenido para adultos'},{id:'adultos-fantasias',nombre:'Fantasías',emoji:'😈',desc:'Contá tus fantasías'},{id:'adultos-rp',nombre:'Roleplay +18',emoji:'🎭',desc:'Juego de roles adultos'},]}];let _curCatId='general';let _curSala=null;let _msgs={};let _listeners={};let _replyTo=null;let _typingTimer=null;let _onlineCounts={};function _esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function _timeAgo(ts){const d=Date.now()-ts;if(d<60000)return'ahora';if(d<3600000)return Math.floor(d/60000)+'m';if(d<86400000)return Math.floor(d/3600000)+'h';return new Date(ts).toLocaleDateString('es-UY',{day:'2-digit',month:'2-digit'});}
function _av(u){if(u?.av&&u.av.startsWith('http'))return`<img src="${_esc(u.av)}" alt="" onerror="this.style.display='none';this.parentNode.textContent='${_esc((u.nick||'?')[0].toUpperCase())}'">`;return _esc((u?.nick||'?')[0].toUpperCase());}
function _isAdultos(salaId){return salaId&&salaId.startsWith('adultos-');}
function _canAccessAdultos(){return!!window.CU;}
window.initSalasPage=function(){renderSalasCats();selectSalasCat('general');};function renderSalasCats(){const el=document.getElementById('salasCatList');if(!el)return;el.innerHTML=SALAS_DATA.map(cat=>`
    <button class="salas-cat-btn${cat.id===_curCatId?' active':''}${cat.adultos?' adultos-cat':''}" 
      onclick="selectSalasCat('${cat.id}')" id="catBtn_${cat.id}">
      <span class="cat-emoji">${cat.emoji}</span>
      <span>${cat.nombre}</span>
      ${cat.adultos?'<span style="font-size:.65rem;background:rgba(255,107,107,.2);color:#ff6b6b;border-radius:4px;padding:1px 5px;margin-left:4px;">+18</span>':''}
    </button>
  `).join('');}
window.selectSalasCat=function(catId){_curCatId=catId;renderSalasCats();const cat=SALAS_DATA.find(c=>c.id===catId);if(!cat)return;renderSalasRooms(cat);};function renderSalasRooms(cat){const el=document.getElementById('salasRoomsList');if(!el)return;const seccTitle=`<div style="font-size:.68rem;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:1px;padding:6px 10px 4px;">${cat.emoji} ${cat.nombre}</div>`;const items=cat.salas.map(s=>`
    <div class="sala-item${_curSala?.id===s.id?' active':''}" id="salaItem_${s.id}" onclick="selectSala('${s.id}','${cat.id}')">
      <span class="sala-hash">#</span>
      <div class="sala-info">
        <div class="sala-name">${_esc(s.nombre)}</div>
        <div class="sala-desc">${_esc(s.desc)}</div>
      </div>
      <span class="sala-online" id="salaOnline_${s.id}">${_onlineCounts[s.id]?_onlineCounts[s.id]+'👤':''}</span>
    </div>
  `).join('');el.innerHTML=seccTitle+items;}
window.selectSala=function(salaId,catId){const cat=SALAS_DATA.find(c=>c.id===catId);const sala=cat?.salas.find(s=>s.id===salaId);if(!sala)return;document.querySelectorAll('.sala-item').forEach(i=>i.classList.remove('active'));const item=document.getElementById('salaItem_'+salaId);if(item)item.classList.add('active');if(cat.adultos&&!_canAccessAdultos()){_showSalaLocked();_curSala=sala;_updateSalaChatHeader(sala);closeSalasSidebar();return;}
_curSala=sala;_showSalaChat();_updateSalaChatHeader(sala);_loadSalaMsgs(sala);closeSalasSidebar();};function _updateSalaChatHeader(sala){const h=document.getElementById('salaChatHeader');if(h)h.style.display='flex';const icon=document.getElementById('salaChatIcon');const name=document.getElementById('salaChatName');const desc=document.getElementById('salaChatDesc');const online=document.getElementById('salaChatOnline');if(icon)icon.textContent=sala.emoji;if(name)name.textContent='#'+sala.nombre;if(desc)desc.textContent=sala.desc;if(online)online.textContent=(_onlineCounts[sala.id]||'?')+' en línea';}
function _showSalaChat(){document.getElementById('salasEmptyState').style.display='none';document.getElementById('salasLockedState').style.display='none';document.getElementById('salaMsgs').style.display='flex';document.getElementById('salaInputWrap').style.display='block';}
function _showSalaLocked(){document.getElementById('salasEmptyState').style.display='none';document.getElementById('salasLockedState').style.display='flex';document.getElementById('salaMsgs').style.display='none';document.getElementById('salaInputWrap').style.display='none';}
function _loadSalaMsgs(sala){const msgsEl=document.getElementById('salaMsgs');if(!msgsEl)return;msgsEl.innerHTML='<div style="text-align:center;padding:20px;color:var(--muted);font-size:.8rem;">Cargando mensajes...</div>';if(_listeners[sala.id]){try{_listeners[sala.id]();}catch(e){}
delete _listeners[sala.id];}
try{var _col=window.collection,_query=window.query,_orderBy=window.orderBy,_limit=window.limit,_onSnap=window.onSnapshot;var db=window.db;if(db&&_col&&_query&&_orderBy&&_limit&&_onSnap){var q=_query(_col(db,'chatSalas',sala.id,'msgs'),_orderBy('ts','asc'),_limit(100));var unsub=_onSnap(q,function(snap){var msgs=[];snap.forEach(function(d){var data=d.data();if(data.ts&&typeof data.ts.toMillis==='function')data.ts=data.ts.toMillis();msgs.push(Object.assign({id:d.id},data));});_msgs[sala.id]=msgs;if(_curSala&&_curSala.id===sala.id)_renderMsgs(msgs);},function(err){console.warn('Sala msgs error:',err);_renderMsgsFallback(sala.id);});_listeners[sala.id]=unsub;}else{_renderMsgsFallback(sala.id);}}catch(e){_renderMsgsFallback(sala.id);}}
function _renderMsgsFallback(salaId){const demos=[{id:'d1',uid:'user1',nick:'Ana García',av:'',text:'¡Hola a todos! 👋',ts:Date.now()-300000,reactions:{}},{id:'d2',uid:'user2',nick:'Carlos M.',av:'',text:'Bienvenid@s a la sala 🎉',ts:Date.now()-200000,reactions:{}},{id:'d3',uid:'user3',nick:'MiLatido Bot',av:'',text:'Esta es una sala de chat en tiempo real. ¡Sé el primero en escribir!',ts:Date.now()-60000,reactions:{}},];_msgs[salaId]=demos;if(_curSala?.id===salaId)_renderMsgs(demos);}
function _renderMsgs(msgs){var el=document.getElementById('salaMsgs');if(!el)return;var atBottom=el.scrollHeight-el.scrollTop-el.clientHeight<80;var prevCount=el.querySelectorAll('.sala-msg').length;if(!msgs||!msgs.length){el.innerHTML='<div style="flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:var(--muted);"><div style="font-size:2.5rem;opacity:.3;">💬</div><div style="font-size:.85rem;">Sé el primero en escribir en esta sala</div></div>';return;}
var cu=window.CU;var html='';var lastDate='';var EMOJIS=['❤️','😂','👍','🔥','😍','😮','😢','👏','🙏','💋'];msgs.forEach(function(m){if(!m||!m.id)return;var ts=m.ts;if(ts&&typeof ts.toMillis==='function')ts=ts.toMillis();if(!ts||typeof ts!=='number')return;var d=new Date(ts);var dateStr=d.toLocaleDateString('es-UY',{day:'2-digit',month:'2-digit',year:'numeric'});if(dateStr!==lastDate){html+='<div class="sala-date-sep">'+dateStr+'</div>';lastDate=dateStr;}
if(m.system){html+='<div class="sala-sys-msg">'+_esc(m.text||'')+'</div>';return;}
var isMine=!!(cu&&m.uid===cu.id);var nick0=_esc((m.nick||'?')[0].toUpperCase());var avHtml=(m.av&&m.av.startsWith('http'))?'<img src="'+_esc(m.av)+'" alt="" onerror="this.style.display=\'none\';this.parentNode.textContent=\''+nick0+'\'">':nick0;var reactions=m.reactions||{};var reactHtml='';Object.keys(reactions).forEach(function(emoji){var uids=reactions[emoji];if(!uids||typeof uids!=='object')return;var count=Object.keys(uids).length;if(count===0)return;var active=(cu&&uids[cu.id])?' active':'';reactHtml+='<span class="sala-msg-reaction'+active+'" onclick="toggleSalaReaction(\''+_esc(m.id)+'\',\''+emoji+'\')">'
+emoji+' <span class="sala-msg-reaction-count">'+count+'</span></span>';});var replyHtml='';if(m.replyTo&&m.replyTo.nick){replyHtml='<div class="sala-msg-reply-preview">↩ <strong>'+_esc(m.replyTo.nick)+':</strong> '+_esc((m.replyTo.text||'').slice(0,60))+'</div>';}
var emojiPops=EMOJIS.map(function(e){return'<span class="sala-react-opt" onclick="toggleSalaReaction(\''+_esc(m.id)+'\',\''+e+'\');closeSalaReactPopups()">'+e+'</span>';}).join('');var delBtn=isMine?'<button class="sala-msg-action-btn" onclick="deleteSalaMsg(\''+_esc(m.id)+'\')">🗑️</button>':'';var safeText=_esc((m.text||'').slice(0,80));var replyBtn='<button class="sala-msg-action-btn" title="Responder" onclick="setSalaReply(\''+_esc(m.id)+'\',\''+_esc(m.nick||'')+'\',\''+safeText+'\')">↩️</button>';html+='<div class="sala-msg" id="salaMsg_'+_esc(m.id)+'" data-uid="'+_esc(m.uid||'')+'">';html+='<div class="sala-msg-av" onclick="openUserProfile(\''+_esc(m.uid||'')+'\',\''+_esc(m.nick||'')+'\')">'+avHtml+'</div>';html+='<div class="sala-msg-body">';html+=replyHtml;html+='<div class="sala-msg-top">';html+='<span class="sala-msg-nick" onclick="openUserProfile(\''+_esc(m.uid||'')+'\',\''+_esc(m.nick||'')+'\')">'+_esc(m.nick||'Anónimo')+'</span>';html+=m.verified?'<img class="sala-msg-verified" src="https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/2705.png">':'';html+='<span class="sala-msg-time">'+_timeAgo(ts)+'</span>';html+='</div>';html+='<div class="sala-msg-text">'+_esc(m.text||'')+'</div>';html+=reactHtml?'<div class="sala-msg-reactions">'+reactHtml+'</div>':'';html+='</div>';html+='<div class="sala-msg-actions">';html+='<button class="sala-msg-action-btn" onclick="showSalaReactPopup(event,\''+_esc(m.id)+'\')">😊</button>';html+=replyBtn+delBtn;html+='</div>';html+='<div class="sala-react-popup" id="reactPop_'+_esc(m.id)+'">'+emojiPops+'</div>';html+='</div>';});el.innerHTML=html;if(atBottom||msgs.length>prevCount){el.scrollTop=el.scrollHeight;}}
window.sendSalaMsg=async function(){if(!window.CU){toast('Iniciá sesión para chatear','err');return;}
if(!_curSala){toast('Selección de sala requerida','err');return;}
var inp=document.getElementById('salaInputText');var text=(inp?inp.value:'').trim();if(!text)return;inp.value='';inp.style.height='';var cu=window.CU;var msg={uid:cu.id,nick:cu.nick||'Usuario',av:cu.av||'',text:text,ts:Date.now(),verified:!!cu.verified,reactions:{}};if(_replyTo){msg.replyTo=Object.assign({},_replyTo);cancelSalaReply();}
var _addDoc=window.addDoc,_col=window.collection,db=window.db;if(!db||!_addDoc||!_col){toast('Sin conexión a Firestore','err');return;}
try{await _addDoc(_col(db,'chatSalas',_curSala.id,'msgs'),msg);}catch(e){console.error('sendSalaMsg error:',e);inp.value=text;toast('No se pudo enviar: '+(e.message||'error'),'err');}};window.handleSalaKey=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendSalaMsg();}};window.autoResizeSalaInput=function(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,120)+'px';};window.setSalaReply=function(msgId,nick,text){_replyTo={msgId,nick,text};document.getElementById('salaReplyBar').classList.add('show');document.getElementById('salaReplyNick').textContent=nick;document.getElementById('salaReplyText').textContent=text;document.getElementById('salaInputText').focus();};window.cancelSalaReply=function(){_replyTo=null;document.getElementById('salaReplyBar').classList.remove('show');};window.showSalaReactPopup=function(e,msgId){e.stopPropagation();closeSalaReactPopups();const pop=document.getElementById('reactPop_'+msgId);if(pop)pop.classList.add('show');setTimeout(()=>document.addEventListener('click',closeSalaReactPopups,{once:true}),10);};window.closeSalaReactPopups=function(){document.querySelectorAll('.sala-react-popup.show').forEach(p=>p.classList.remove('show'));};window.toggleSalaReaction=async function(msgId,emoji){if(!window.CU){toast('Iniciá sesión para reaccionar','err');return;}
if(!_curSala)return;if(!msgId||msgId.startsWith('local_'))return;var _doc=window.doc,_updateDoc=window.updateDoc,_getDoc=window.getDoc,db=window.db;if(!db||!_doc||!_updateDoc||!_getDoc){console.warn('Firestore no disponible para reacciones');return;}
var uid=window.CU.id;var localMsg=(_msgs[_curSala.id]||[]).find(function(m){return m.id===msgId;});if(localMsg){if(!localMsg.reactions)localMsg.reactions={};if(!localMsg.reactions[emoji])localMsg.reactions[emoji]={};if(localMsg.reactions[emoji][uid])delete localMsg.reactions[emoji][uid];else localMsg.reactions[emoji][uid]=true;if(Object.keys(localMsg.reactions[emoji]).length===0)delete localMsg.reactions[emoji];_renderMsgs(_msgs[_curSala.id]);}
try{var msgRef=_doc(db,'chatSalas',_curSala.id,'msgs',msgId);var snap=await _getDoc(msgRef);if(!snap.exists())return;var reactions=snap.data().reactions||{};if(!reactions[emoji])reactions[emoji]={};if(reactions[emoji][uid])delete reactions[emoji][uid];else reactions[emoji][uid]=true;if(Object.keys(reactions[emoji]).length===0)delete reactions[emoji];await _updateDoc(msgRef,{reactions:reactions});}catch(e){console.error('Reaction error:',e);if(localMsg&&localMsg.reactions&&localMsg.reactions[emoji]){if(localMsg.reactions[emoji][uid])delete localMsg.reactions[emoji][uid];else localMsg.reactions[emoji][uid]=true;if(Object.keys(localMsg.reactions[emoji]).length===0)delete localMsg.reactions[emoji];_renderMsgs(_msgs[_curSala.id]);}
if(typeof toast==='function')toast('Error al reaccionar','err');}};window.deleteSalaMsg=async function(msgId){if(!confirm('¿Eliminar este mensaje?'))return;const _doc=window.doc,_deleteDoc=window.deleteDoc,db=window.db;if(!db||!_doc||!_deleteDoc)return;try{await _deleteDoc(_doc(db,'chatSalas',_curSala.id,'msgs',msgId));}catch(e){console.warn('Delete error:',e);if(typeof toast==='function')toast('No se pudo eliminar','err');}};window.onSalaTyping=function(){clearTimeout(_typingTimer);};let _presenceSalaUnsub=null;let _presenceSalaInterval=null;function _writeSalaPresence(salaId){if(!window.CU||!window.db)return;var _doc=window.doc,_setDoc=window.setDoc;if(!_doc||!_setDoc)return;try{_setDoc(_doc(window.db,'salaPresence',salaId+'_'+window.CU.id),{salaId:salaId,uid:window.CU.id,nick:window.CU.nick||'',ts:Date.now()},{merge:true}).catch(function(){});}catch(e){}}
function _removeSalaPresence(salaId){if(!window.CU||!window.db)return;var _doc=window.doc,_deleteDoc=window.deleteDoc;if(!_doc||!_deleteDoc)return;try{_deleteDoc(_doc(window.db,'salaPresence',salaId+'_'+window.CU.id)).catch(function(){});}catch(e){}}
function _subscribeAllSalaPresence(){if(!window.db)return;if(_presenceSalaUnsub){try{_presenceSalaUnsub();}catch(e){}_presenceSalaUnsub=null;}
try{var _onSnap=window.onSnapshot,_col=window.collection;if(!_onSnap||!_col)return;_presenceSalaUnsub=_onSnap(_col(window.db,'salaPresence'),function(snap){var counts={};var now=Date.now();snap.forEach(function(d){var data=d.data();if(data.salaId&&data.ts&&(now-data.ts)<120000){counts[data.salaId]=(counts[data.salaId]||0)+1;}});_onlineCounts=counts;document.querySelectorAll('[id^="salaOnline_"]').forEach(function(el){var sId=el.id.replace('salaOnline_','');el.textContent=counts[sId]?counts[sId]+'👥':'';});if(_curSala){var onlineEl=document.getElementById('salaChatOnline');if(onlineEl)onlineEl.textContent=(_onlineCounts[_curSala.id]||1)+' en línea';}},function(err){console.warn('salaPresence error:',err);});}catch(e){console.warn('_subscribeAllSalaPresence error:',e);}}
const _origSelectSala=window.selectSala;window.selectSala=function(salaId,catId){if(_curSala&&_curSala.id!==salaId)_removeSalaPresence(_curSala.id);clearInterval(_presenceSalaInterval);_origSelectSala(salaId,catId);_writeSalaPresence(salaId);_presenceSalaInterval=setInterval(()=>_writeSalaPresence(salaId),60000);_subscribeAllSalaPresence();};window.addEventListener('beforeunload',()=>{if(_curSala)_removeSalaPresence(_curSala.id);});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(_curSala)_removeSalaPresence(_curSala.id);}
else{if(_curSala)_writeSalaPresence(_curSala.id);}});window.insertSalaEmoji=function(emoji){const inp=document.getElementById('salaInputText');if(!inp)return;const start=inp.selectionStart||0;const val=inp.value;inp.value=val.slice(0,start)+emoji+val.slice(inp.selectionEnd||start);inp.selectionStart=inp.selectionEnd=start+emoji.length;inp.focus();};window.openSalasSidebar=function(){document.getElementById('salasSidebar').classList.add('mob-open');document.getElementById('salaMobOverlay').classList.add('show');};window.closeSalasSidebar=function(){document.getElementById('salasSidebar').classList.remove('mob-open');document.getElementById('salaMobOverlay').classList.remove('show');};window.initSalasPage=window.initSalasPage;})();